image: base/devel

stages:
  - sync
  - build
  - test

.job_templates:
  .variables_template: &default_variables
    C_COMPILER: gcc
    CXX_COMPILER: g++
    BUILD_TYPE: Debug
    BUILD_REFERENCE: "ON"
    BUILD_CPU: "OFF"
    BUILD_GPU: "OFF"
    EXTRA_PACKAGES: ""

  .build_template: &default_build
    stage: build
    variables: *default_variables
    before_script:
      - pacman-db-upgrade
      - pacman --noconfirm -Syu cmake git ${EXTRA_PACKAGES}
    script:
      - mkdir -p ${CI_JOB_NAME} && cd ${CI_JOB_NAME}
      - cmake ${CI_PROJECT_DIR}
          -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DDEVEL_TOOLS=OFF
          -DBUILD_REFERENCE=${BUILD_REFERENCE} -DBUILD_CPU=${BUILD_CPU}
          -DBUILD_GPU=${BUILD_GPU}
          -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
      - make -j$(grep "core id" /proc/cpuinfo | sort -u | wc -l)
    artifacts:
      paths:
        - build/

  .test_template: &default_test
    stage: test
    script:
      - cd ${CI_JOB_NAME/test/build}
      - make test

build/gcc/reference/debug:
  <<: *default_build

build/clang/reference/debug:
  <<: *default_build
  variables:
    <<: *default_variables
    C_COMPILER: clang
    CXX_COMPILER: clang++
    EXTRA_PACKAGES: clang


test/gcc/reference/debug:
  <<: *default_test
  dependencies:
    - build/gcc/reference/debug

test/clang/reference/debug:
  <<: *default_test
  dependencies:
    - build/clang/reference/debug
