image: base/devel

stages:
  - sync
  - build
  - test

before_script:
  - pacman-db-upgrade
  - pacman --noconfirm -Syu cmake git clang

build/gcc/reference/debug:
  stage: build
  variables:
    C_COMPILER: gcc
    CXX_COMPILER: g++
    BUILD_TYPE: Debug
    MODULES: -DBUILD_REFERENCE=ON -DBUILD_CPU=OFF -DBUILD_GPU=OFF
  script: &build_script
    - mkdir -p ${CI_JOB_NAME} && cd ${CI_JOB_NAME}
    - cmake ${CI_PROJECT_DIR}
        -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DDEVEL_TOOLS=OFF
        ${MODULES}
        -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
    - make -j$(grep "core id" /proc/cpuinfo | sort -u | wc -l)
  artifacts: &build_dir
    paths:
      - build/

build/clang/reference/debug:
  stage: build
  variables:
    C_COMPILER: clang
    CXX_COMPILER: clang++
    BUILD_TYPE: Debug
    MODULES: -DBUILD_REFERENCE=ON -DBUILD_CPU=OFF -DBUILD_GPU=OFF
  script: *build_script
  artifacts: *build_dir


test/gcc/reference/debug:
  stage: test
  dependencies:
    - build/gcc/reference/debug
  script: &test_script
    - cd ${CI_JOB_NAME/test/build}
    - make test

test/clang/reference/debug:
  stage: test
  dependencies:
    - build/clang/reference/debug
  script: *test_script
