name: Windows-build

on: [push]

jobs:
  windows_cuda:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {version: "10.2.89.20191206", name: "cuda102/release/shared"}
        - {version: "latest", name: "cuda-latest/release/shared"}
    name: msvc/${{ matrix.config.name }} (only compile)
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: setup (versioned)
      if: matrix.config.version != 'latest'
      run: |
        choco install cuda --version=${{ matrix.config.version }} -y
    - name: setup (latest)
      if: matrix.config.version == 'latest'
      run: |
        choco install cuda -y
    - name: configure
      run: |
        "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin/nvcc.exe" --help
      shell: cmd